/home/pi/node/jsRegister/db.js:36
    log(__line__,'SQL',qname, sql);
    ^

ReferenceError: log is not defined
    at Object.sql (/home/pi/node/jsRegister/db.js:36:5)
    at Socket.<anonymous> (/home/pi/node/jsRegister/app.js:133:8)
    at Socket.emit (events.js:198:13)
    at /home/pi/node/jsRegister/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'spdy'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/node/jsRegister/app.js:10:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'secure-random-string'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/node/jsRegister/func.js:3:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'secure-random-string'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/node/jsRegister/func.js:3:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::1992
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Object.<anonymous> (/home/pi/node/jsRegister/app.js:81:46)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
Emitted 'error' event at:
    at Server.emit (/home/pi/node/jsRegister/node_modules/spdy/lib/spdy/server.js:236:40)
    at emitErrorNT (net.js:1307:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
/home/pi/node/jsRegister/app.js:14
var app               = express(),
^^^

SyntaxError: Unexpected token var
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'spdy'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/node/jsRegister/app.js:10:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

TypeError: callback is not a function
    at Query.<anonymous> (/home/pi/node/jsRegister/db.js:40:9)
    at Query.<anonymous> (/home/pi/node/jsRegister/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/pi/node/jsRegister/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/pi/node/jsRegister/node_modules/mysql/lib/Connection.js:88:28)
/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'pmd'@'192.168.1.52' (using password: NO)
    at Handshake.Sequence._packetToError (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/pi/node/jsRegister/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/pi/node/jsRegister/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
    --------------------
    at Protocol._enqueue (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/home/pi/node/jsRegister/node_modules/mysql/lib/Connection.js:116:18)
    at Object.<anonymous> (/home/pi/node/jsRegister/db.js:20:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
Emitted 'error' event at:
    at Connection._handleProtocolError (/home/pi/node/jsRegister/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:198:13)
    at Protocol._delegateError (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Handshake.<anonymous> (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:153:12)
    at Handshake.emit (events.js:198:13)
    at Handshake.Sequence.end (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:12)
    at Handshake.ErrorPacket (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/sequences/Handshake.js:125:8)
    at Protocol._parsePacket (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Parser.js:43:10)
/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'pmd'@'192.168.1.52' (using password: NO)
    at Handshake.Sequence._packetToError (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/pi/node/jsRegister/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/pi/node/jsRegister/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
    --------------------
    at Protocol._enqueue (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/home/pi/node/jsRegister/node_modules/mysql/lib/Connection.js:116:18)
    at Object.<anonymous> (/home/pi/node/jsRegister/db.js:20:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
Emitted 'error' event at:
    at Connection._handleProtocolError (/home/pi/node/jsRegister/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:198:13)
    at Protocol._delegateError (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Handshake.<anonymous> (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:153:12)
    at Handshake.emit (events.js:198:13)
    at Handshake.Sequence.end (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:12)
    at Handshake.ErrorPacket (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/sequences/Handshake.js:125:8)
    at Protocol._parsePacket (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Parser.js:43:10)
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: connect EHOSTUNREACH 192.168.1.100:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
    --------------------
    at Protocol._enqueue (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/home/pi/node/jsRegister/node_modules/mysql/lib/Connection.js:116:18)
    at Object.<anonymous> (/home/pi/node/jsRegister/db.js:20:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
Emitted 'error' event at:
    at Connection._handleProtocolError (/home/pi/node/jsRegister/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:198:13)
    at Protocol._delegateError (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Handshake.<anonymous> (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:153:12)
    at Handshake.emit (events.js:198:13)
    at Handshake.Sequence.end (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:12)
    at Protocol.handleNetworkError (/home/pi/node/jsRegister/node_modules/mysql/lib/protocol/Protocol.js:369:14)
    at Connection._handleNetworkError (/home/pi/node/jsRegister/node_modules/mysql/lib/Connection.js:418:18)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
